# -*- coding: utf-8 -*-
"""lean_python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13s2jbzuPu7WznuEof7TCuQsLBwM-vC1S
"""

import pandas as pd

path = '/content/drive/MyDrive/lean.csv'
data = pd.read_csv(path)
data.head()

data.columns[1:]

data['Total'] = data['Maths'] + data['Biology'] + data['English'] + data['Physics'] + data['Chemistry'] + data['Hindi']
data.head()



# Topper in Each Subjects

for i in data.columns[1:-1]:
  topper = data.loc[data[i] == data[i].max()]['Name'].values
  print("Topper in {} is {}".format(i,topper))

toppers = data.sort_values(['Total'],ascending=False)['Name'].head(3).values
print("Best students in the class are {} first rank, {} second rank, {} third rank".format(toppers[0],toppers[1],toppers[2]))

